/* Auto-generated by utensor cli */
#ifndef __MNIST_CNN_MODEL_INTERFACE_H
#define __MNIST_CNN_MODEL_INTERFACE_H
#include "uTensor.h"

using namespace uTensor;

class Mnist_cnn_model : public ModelInterface<1, 1> 
{
 public:
  enum input_names : uint8_t { input_0 };
  enum output_names : uint8_t { output_0 };
  Mnist_cnn_model();
 protected:
  virtual void compute();
 private:
  // Operators
  ReferenceOperators::ReshapeOperator<int8_t> op_ReshapeOperator_000;

  TflmSymQuantOps::QuantizeOperator<int8_t, float> op_QuantizeOperator_001;

  TflmSymQuantOps::DequantizeOperator<float, int8_t> op_DequantizeOperator_002;

  TflmSymQuantOps::DepthwiseSeparableConvOperator<int8_t> op_DepthwiseSeparableConvOperator_003;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_004;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_005;

  ReferenceOperators::MaxPoolOperator<int8_t> op_MaxPoolOperator_006;

  // memory allocators
  localCircularArenaAllocator<3080, uint16_t> ram_allocator;
  localCircularArenaAllocator<960, uint16_t> metadata_allocator;
};

#endif // __MNIST_CNN_MODEL_INTERFACE_H