/* Auto-generated by utensor cli */
#ifndef __MNIST_MODEL_INTERFACE_H
#define __MNIST_MODEL_INTERFACE_H
#include "uTensor.h"

using namespace uTensor;

class Mnist_cnn_model : public ModelInterface<1, 1> 
{
 public:
  enum input_names : uint8_t { input_0 };
  enum output_names : uint8_t { output_0 };
  Mnist_cnn_model();
 protected:
  virtual void compute();
 private:
  // Operators
  ReferenceOperators::Conv2dOperator<int8_t> op_Conv2dOperator_000;

  TflmSymQuantOps::DequantizeOperator<float, int8_t> op_DequantizeOperator_001;

  TflmSymQuantOps::DepthwiseSeparableConvOperator<int8_t> op_DepthwiseSeparableConvOperator_002;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_003;

  ReferenceOperators::ReshapeOperator<int8_t> op_ReshapeOperator_004;

  TflmSymQuantOps::QuantizeOperator<int8_t, float> op_QuantizeOperator_005;

  ReferenceOperators::MaxPoolOperator<int8_t> op_MaxPoolOperator_006;

  ReferenceOperators::ReLUOperator<int8_t> op_ReLUOperator_007;

  TflmSymQuantOps::FullyConnectedOperator<int8_t> op_FullyConnectedOperator_008;

  // memory allocators
  localCircularArenaAllocator<4824, uint16_t> ram_allocator;
  localCircularArenaAllocator<1152, uint16_t> metadata_allocator;
};

#endif // __MNIST_MODEL_INTERFACE_H
